name: Check for NONE

on:
  workflow_dispatch:
  schedule:
    - cron: 0 17 * * THU

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  check-for-none:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v6.0.2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1.295.0
      with:
        bundler-cache: true
    - name: Check for NONE
      run: bundle exec ruby rb/check_for_none.rb
    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Auto-adjusting NONE disco
  jekyll:
    needs: check-for-none
    uses: ./.github/workflows/jekyll.yml
